
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:45 GMT 2016 ///

/// class java.util.concurrent.AbstractExecutorService ///

open class AbstractExecutorService: java_lang.JavaObject, ExecutorService {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.util.concurrent.AbstractExecutorService", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AbstractExecutorServiceJNIClass: jclass?

    /// static final boolean java.util.concurrent.AbstractExecutorService.$assertionsDisabled

    /// public java.util.concurrent.AbstractExecutorService()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "java/util/concurrent/AbstractExecutorService", classCache: &AbstractExecutorService.AbstractExecutorServiceJNIClass, methodSig: "()V", methodCache: &AbstractExecutorService.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// protected java.util.concurrent.RunnableFuture java.util.concurrent.AbstractExecutorService.newTaskFor(java.util.concurrent.Callable)

    private static var newTaskFor_MethodID_2: jmethodID?

    open func newTaskFor( arg0: Callable? ) -> RunnableFuture! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "newTaskFor", methodSig: "(Ljava/util/concurrent/Callable;)Ljava/util/concurrent/RunnableFuture;", methodCache: &AbstractExecutorService.newTaskFor_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? RunnableFutureForward( javaObject: __return ) : nil
    }

    open func newTaskFor( _ _arg0: Callable? ) -> RunnableFuture! {
        return newTaskFor( arg0: _arg0 )
    }

    /// protected java.util.concurrent.RunnableFuture java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)

    private static var newTaskFor_MethodID_3: jmethodID?

    open func newTaskFor( arg0: java_lang.Runnable?, arg1: java_lang.JavaObject? ) -> RunnableFuture! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "newTaskFor", methodSig: "(Ljava/lang/Runnable;Ljava/lang/Object;)Ljava/util/concurrent/RunnableFuture;", methodCache: &AbstractExecutorService.newTaskFor_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? RunnableFutureForward( javaObject: __return ) : nil
    }

    open func newTaskFor( _ _arg0: java_lang.Runnable?, _ _arg1: java_lang.JavaObject? ) -> RunnableFuture! {
        return newTaskFor( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.util.concurrent.Future java.util.concurrent.AbstractExecutorService.submit(java.lang.Runnable,java.lang.Object)

    private static var submit_MethodID_4: jmethodID?

    open func submit( arg0: java_lang.Runnable?, arg1: java_lang.JavaObject? ) -> Future! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "submit", methodSig: "(Ljava/lang/Runnable;Ljava/lang/Object;)Ljava/util/concurrent/Future;", methodCache: &AbstractExecutorService.submit_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FutureForward( javaObject: __return ) : nil
    }

    open func submit( _ _arg0: java_lang.Runnable?, _ _arg1: java_lang.JavaObject? ) -> Future! {
        return submit( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.util.concurrent.Future java.util.concurrent.AbstractExecutorService.submit(java.util.concurrent.Callable)

    private static var submit_MethodID_5: jmethodID?

    open func submit( arg0: Callable? ) -> Future! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "submit", methodSig: "(Ljava/util/concurrent/Callable;)Ljava/util/concurrent/Future;", methodCache: &AbstractExecutorService.submit_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FutureForward( javaObject: __return ) : nil
    }

    open func submit( _ _arg0: Callable? ) -> Future! {
        return submit( arg0: _arg0 )
    }

    /// public java.util.concurrent.Future java.util.concurrent.AbstractExecutorService.submit(java.lang.Runnable)

    private static var submit_MethodID_6: jmethodID?

    open func submit( arg0: java_lang.Runnable? ) -> Future! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "submit", methodSig: "(Ljava/lang/Runnable;)Ljava/util/concurrent/Future;", methodCache: &AbstractExecutorService.submit_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FutureForward( javaObject: __return ) : nil
    }

    open func submit( _ _arg0: java_lang.Runnable? ) -> Future! {
        return submit( arg0: _arg0 )
    }

    /// private java.lang.Object java.util.concurrent.AbstractExecutorService.doInvokeAny(java.util.Collection,boolean,long) throws java.lang.InterruptedException,java.util.concurrent.ExecutionException,java.util.concurrent.TimeoutException

    /// public java.lang.Object java.util.concurrent.AbstractExecutorService.invokeAny(java.util.Collection) throws java.lang.InterruptedException,java.util.concurrent.ExecutionException

    private static var invokeAny_MethodID_7: jmethodID?

    open func invokeAny( arg0: Collection? ) throws /* java.lang.InterruptedException, java.util.concurrent.ExecutionException */ -> java_lang.JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "invokeAny", methodSig: "(Ljava/util/Collection;)Ljava/lang/Object;", methodCache: &AbstractExecutorService.invokeAny_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.InterruptedException( javaObject: throwable )
        }
        return __return != nil ? java_lang.JavaObject( javaObject: __return ) : nil
    }

    open func invokeAny( _ _arg0: Collection? ) throws /* java.lang.InterruptedException, java.util.concurrent.ExecutionException */ -> java_lang.JavaObject! {
        return try invokeAny( arg0: _arg0 )
    }

    /// public java.lang.Object java.util.concurrent.AbstractExecutorService.invokeAny(java.util.Collection,long,java.util.concurrent.TimeUnit) throws java.lang.InterruptedException,java.util.concurrent.ExecutionException,java.util.concurrent.TimeoutException

    private static var invokeAny_MethodID_8: jmethodID?

    open func invokeAny( arg0: Collection?, arg1: Int64, arg2: TimeUnit? ) throws /* java.lang.InterruptedException, java.util.concurrent.ExecutionException, java.util.concurrent.TimeoutException */ -> java_lang.JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        __args[2] = JNIType.encode( value: arg2, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "invokeAny", methodSig: "(Ljava/util/Collection;JLjava/util/concurrent/TimeUnit;)Ljava/lang/Object;", methodCache: &AbstractExecutorService.invokeAny_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.InterruptedException( javaObject: throwable )
        }
        return __return != nil ? java_lang.JavaObject( javaObject: __return ) : nil
    }

    open func invokeAny( _ _arg0: Collection?, _ _arg1: Int64, _ _arg2: TimeUnit? ) throws /* java.lang.InterruptedException, java.util.concurrent.ExecutionException, java.util.concurrent.TimeoutException */ -> java_lang.JavaObject! {
        return try invokeAny( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// public java.util.List java.util.concurrent.AbstractExecutorService.invokeAll(java.util.Collection) throws java.lang.InterruptedException

    private static var invokeAll_MethodID_9: jmethodID?

    open func invokeAll( arg0: Collection? ) throws /* java.lang.InterruptedException */ -> List! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "invokeAll", methodSig: "(Ljava/util/Collection;)Ljava/util/List;", methodCache: &AbstractExecutorService.invokeAll_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.InterruptedException( javaObject: throwable )
        }
        return __return != nil ? ListForward( javaObject: __return ) : nil
    }

    open func invokeAll( _ _arg0: Collection? ) throws /* java.lang.InterruptedException */ -> List! {
        return try invokeAll( arg0: _arg0 )
    }

    /// public java.util.List java.util.concurrent.AbstractExecutorService.invokeAll(java.util.Collection,long,java.util.concurrent.TimeUnit) throws java.lang.InterruptedException

    private static var invokeAll_MethodID_10: jmethodID?

    open func invokeAll( arg0: Collection?, arg1: Int64, arg2: TimeUnit? ) throws /* java.lang.InterruptedException */ -> List! {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        __args[2] = JNIType.encode( value: arg2, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "invokeAll", methodSig: "(Ljava/util/Collection;JLjava/util/concurrent/TimeUnit;)Ljava/util/List;", methodCache: &AbstractExecutorService.invokeAll_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.InterruptedException( javaObject: throwable )
        }
        return __return != nil ? ListForward( javaObject: __return ) : nil
    }

    open func invokeAll( _ _arg0: Collection?, _ _arg1: Int64, _ _arg2: TimeUnit? ) throws /* java.lang.InterruptedException */ -> List! {
        return try invokeAll( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// In declared protocol but not defined.. ///

    /// public abstract boolean java.util.concurrent.ExecutorService.awaitTermination(long,java.util.concurrent.TimeUnit) throws java.lang.InterruptedException

    private static var awaitTermination_MethodID_11: jmethodID?

    open func awaitTermination( arg0: Int64, arg1: TimeUnit? ) throws /* java.lang.InterruptedException */ -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "awaitTermination", methodSig: "(JLjava/util/concurrent/TimeUnit;)Z", methodCache: &AbstractExecutorService.awaitTermination_MethodID_11, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.InterruptedException( javaObject: throwable )
        }
        return JNIType.decode( type: Bool(), from: __return )
    }

    open func awaitTermination( _ _arg0: Int64, _ _arg1: TimeUnit? ) throws /* java.lang.InterruptedException */ -> Bool {
        return try awaitTermination( arg0: _arg0, arg1: _arg1 )
    }

    /// public abstract void java.util.concurrent.ExecutorService.shutdown()

    private static var shutdown_MethodID_12: jmethodID?

    open func shutdown() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "shutdown", methodSig: "()V", methodCache: &AbstractExecutorService.shutdown_MethodID_12, args: &__args, locals: &__locals )
    }


    /// public abstract boolean java.util.concurrent.ExecutorService.isShutdown()

    private static var isShutdown_MethodID_13: jmethodID?

    open func isShutdown() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isShutdown", methodSig: "()Z", methodCache: &AbstractExecutorService.isShutdown_MethodID_13, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public abstract java.util.List java.util.concurrent.ExecutorService.shutdownNow()

    private static var shutdownNow_MethodID_14: jmethodID?

    open func shutdownNow() -> List! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "shutdownNow", methodSig: "()Ljava/util/List;", methodCache: &AbstractExecutorService.shutdownNow_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? ListForward( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.concurrent.ExecutorService.isTerminated()

    private static var isTerminated_MethodID_15: jmethodID?

    open func isTerminated() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isTerminated", methodSig: "()Z", methodCache: &AbstractExecutorService.isTerminated_MethodID_15, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public abstract void java.util.concurrent.Executor.execute(java.lang.Runnable)

    private static var execute_MethodID_16: jmethodID?

    open func execute( arg0: java_lang.Runnable? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "execute", methodSig: "(Ljava/lang/Runnable;)V", methodCache: &AbstractExecutorService.execute_MethodID_16, args: &__args, locals: &__locals )
    }

    open func execute( _ _arg0: java_lang.Runnable? ) {
        execute( arg0: _arg0 )
    }

}
