
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:55 GMT 2016 ///

/// class java.util.zip.CheckedInputStream ///

open class CheckedInputStream: /* java.io.FilterInputStream */ UnclassedObject {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.util.zip.CheckedInputStream", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var CheckedInputStreamJNIClass: jclass?

    /// private java.util.zip.Checksum java.util.zip.CheckedInputStream.cksum

    /// protected volatile java.io.InputStream java.io.FilterInputStream.in

    private static var _in_FieldID: jfieldID?

    open var _in: /* java.io.InputStream */ UnclassedObject! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "in", fieldType: "Ljava/io/InputStream;", fieldCache: &CheckedInputStream._in_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? /* java.io.InputStream */ UnclassedObject( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.encode( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "in", fieldType: "Ljava/io/InputStream;", fieldCache: &CheckedInputStream._in_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private static final int java.io.InputStream.MAX_SKIP_BUFFER_SIZE

    /// public java.util.zip.CheckedInputStream(java.io.InputStream,java.util.zip.Checksum)

    private static var new_MethodID_1: jmethodID?

    public convenience init( arg0: /* java.io.InputStream */ UnclassedObject?, arg1: Checksum? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = jvalue( l: arg1?.localJavaObject( &__locals ) )
        let __object = JNIMethod.NewObject( className: "java/util/zip/CheckedInputStream", classCache: &CheckedInputStream.CheckedInputStreamJNIClass, methodSig: "(Ljava/io/InputStream;Ljava/util/zip/Checksum;)V", methodCache: &CheckedInputStream.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: /* java.io.InputStream */ UnclassedObject?, _ _arg1: Checksum? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// public int java.util.zip.CheckedInputStream.read() throws java.io.IOException

    /// public int java.util.zip.CheckedInputStream.read(byte[],int,int) throws java.io.IOException

    /// public long java.util.zip.CheckedInputStream.skip(long) throws java.io.IOException

    /// public java.util.zip.Checksum java.util.zip.CheckedInputStream.getChecksum()

    private static var getChecksum_MethodID_2: jmethodID?

    open func getChecksum() -> Checksum! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getChecksum", methodSig: "()Ljava/util/zip/Checksum;", methodCache: &CheckedInputStream.getChecksum_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? ChecksumForward( javaObject: __return ) : nil
    }


}
