
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.util.Deque ///

public protocol Deque: Queue {

    /// public abstract boolean java.util.Deque.add(java.lang.Object)

    func add( e: java_swift.JavaObject? ) -> Bool

    /// public abstract void java.util.Deque.addFirst(java.lang.Object)

    func addFirst( e: java_swift.JavaObject? )

    /// public abstract void java.util.Deque.addLast(java.lang.Object)

    func addLast( e: java_swift.JavaObject? )

    /// public abstract boolean java.util.Deque.contains(java.lang.Object)

    func contains( o: java_swift.JavaObject? ) -> Bool

    /// public abstract java.util.Iterator java.util.Deque.descendingIterator()

    func descendingIterator() -> Iterator!

    /// public abstract java.lang.Object java.util.Deque.element()

    func element() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.getFirst()

    func getFirst() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.getLast()

    func getLast() -> java_swift.JavaObject!

    /// public abstract java.util.Iterator java.util.Deque.iterator()

    func iterator() -> Iterator!

    /// public abstract boolean java.util.Deque.offer(java.lang.Object)

    func offer( e: java_swift.JavaObject? ) -> Bool

    /// public abstract boolean java.util.Deque.offerFirst(java.lang.Object)

    func offerFirst( e: java_swift.JavaObject? ) -> Bool

    /// public abstract boolean java.util.Deque.offerLast(java.lang.Object)

    func offerLast( e: java_swift.JavaObject? ) -> Bool

    /// public abstract java.lang.Object java.util.Deque.peek()

    func peek() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.peekFirst()

    func peekFirst() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.peekLast()

    func peekLast() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.poll()

    func poll() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.pollFirst()

    func pollFirst() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.pollLast()

    func pollLast() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.pop()

    func pop() -> java_swift.JavaObject!

    /// public abstract void java.util.Deque.push(java.lang.Object)

    func push( e: java_swift.JavaObject? )

    /// public abstract boolean java.util.Deque.remove(java.lang.Object)

    func remove( o: java_swift.JavaObject? ) -> Bool

    /// public abstract java.lang.Object java.util.Deque.remove()

    func remove() -> java_swift.JavaObject!

    /// public abstract java.lang.Object java.util.Deque.removeFirst()

    func removeFirst() -> java_swift.JavaObject!

    /// public abstract boolean java.util.Deque.removeFirstOccurrence(java.lang.Object)

    func removeFirstOccurrence( o: java_swift.JavaObject? ) -> Bool

    /// public abstract java.lang.Object java.util.Deque.removeLast()

    func removeLast() -> java_swift.JavaObject!

    /// public abstract boolean java.util.Deque.removeLastOccurrence(java.lang.Object)

    func removeLastOccurrence( o: java_swift.JavaObject? ) -> Bool

    /// public abstract int java.util.Deque.size()

    func size() -> Int

}


open class DequeForward: QueueForward, Deque {

    private static var DequeJNIClass: jclass?

    /// public abstract boolean java.util.Deque.add(java.lang.Object)

    private static var add_MethodID_28: jmethodID?

    override open func add( e: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "add", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.add_MethodID_28, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func add( _ _e: java_swift.JavaObject? ) -> Bool {
        return add( e: _e )
    }

    /// public abstract boolean java.util.Collection.addAll(java.util.Collection)

    private static var addAll_MethodID_29: jmethodID?

    override open func addAll( c: Collection? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: c, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "addAll", methodSig: "(Ljava/util/Collection;)Z", methodCache: &DequeForward.addAll_MethodID_29, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func addAll( _ _c: Collection? ) -> Bool {
        return addAll( c: _c )
    }

    /// public abstract void java.util.Deque.addFirst(java.lang.Object)

    private static var addFirst_MethodID_30: jmethodID?

    open func addFirst( e: java_swift.JavaObject? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "addFirst", methodSig: "(Ljava/lang/Object;)V", methodCache: &DequeForward.addFirst_MethodID_30, args: &__args, locals: &__locals )
    }

    open func addFirst( _ _e: java_swift.JavaObject? ) {
        addFirst( e: _e )
    }

    /// public abstract void java.util.Deque.addLast(java.lang.Object)

    private static var addLast_MethodID_31: jmethodID?

    open func addLast( e: java_swift.JavaObject? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "addLast", methodSig: "(Ljava/lang/Object;)V", methodCache: &DequeForward.addLast_MethodID_31, args: &__args, locals: &__locals )
    }

    open func addLast( _ _e: java_swift.JavaObject? ) {
        addLast( e: _e )
    }

    /// public abstract void java.util.Collection.clear()

    private static var clear_MethodID_32: jmethodID?

    override open func clear() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "clear", methodSig: "()V", methodCache: &DequeForward.clear_MethodID_32, args: &__args, locals: &__locals )
    }


    /// public abstract boolean java.util.Deque.contains(java.lang.Object)

    private static var contains_MethodID_33: jmethodID?

    override open func contains( o: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: o, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "contains", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.contains_MethodID_33, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func contains( _ _o: java_swift.JavaObject? ) -> Bool {
        return contains( o: _o )
    }

    /// public abstract boolean java.util.Collection.containsAll(java.util.Collection)

    private static var containsAll_MethodID_34: jmethodID?

    override open func containsAll( c: Collection? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: c, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "containsAll", methodSig: "(Ljava/util/Collection;)Z", methodCache: &DequeForward.containsAll_MethodID_34, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func containsAll( _ _c: Collection? ) -> Bool {
        return containsAll( c: _c )
    }

    /// public abstract java.util.Iterator java.util.Deque.descendingIterator()

    private static var descendingIterator_MethodID_35: jmethodID?

    open func descendingIterator() -> Iterator! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "descendingIterator", methodSig: "()Ljava/util/Iterator;", methodCache: &DequeForward.descendingIterator_MethodID_35, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? IteratorForward( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.element()

    private static var element_MethodID_36: jmethodID?

    override open func element() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "element", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.element_MethodID_36, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.Collection.equals(java.lang.Object)

    private static var equals_MethodID_37: jmethodID?

    override open func equals( o: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: o, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "equals", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.equals_MethodID_37, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func equals( _ _o: java_swift.JavaObject? ) -> Bool {
        return equals( o: _o )
    }

    /// public default void java.lang.Iterable.forEach(java.util.function.Consumer)

    private static var forEach_MethodID_38: jmethodID?

    override open func forEach( action: Consumer? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: action, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "forEach", methodSig: "(Ljava/util/function/Consumer;)V", methodCache: &DequeForward.forEach_MethodID_38, args: &__args, locals: &__locals )
    }

    override open func forEach( _ _action: Consumer? ) {
        forEach( action: _action )
    }

    /// public abstract java.lang.Object java.util.Deque.getFirst()

    private static var getFirst_MethodID_39: jmethodID?

    open func getFirst() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getFirst", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.getFirst_MethodID_39, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.getLast()

    private static var getLast_MethodID_40: jmethodID?

    open func getLast() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getLast", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.getLast_MethodID_40, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract int java.util.Collection.hashCode()

    private static var hashCode_MethodID_41: jmethodID?

    override open func hashCode() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "hashCode", methodSig: "()I", methodCache: &DequeForward.hashCode_MethodID_41, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract boolean java.util.Collection.isEmpty()

    private static var isEmpty_MethodID_42: jmethodID?

    override open func isEmpty() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isEmpty", methodSig: "()Z", methodCache: &DequeForward.isEmpty_MethodID_42, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public abstract java.util.Iterator java.util.Deque.iterator()

    private static var iterator_MethodID_43: jmethodID?

    override open func iterator() -> Iterator! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "iterator", methodSig: "()Ljava/util/Iterator;", methodCache: &DequeForward.iterator_MethodID_43, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? IteratorForward( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.Deque.offer(java.lang.Object)

    private static var offer_MethodID_44: jmethodID?

    override open func offer( e: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "offer", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.offer_MethodID_44, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func offer( _ _e: java_swift.JavaObject? ) -> Bool {
        return offer( e: _e )
    }

    /// public abstract boolean java.util.Deque.offerFirst(java.lang.Object)

    private static var offerFirst_MethodID_45: jmethodID?

    open func offerFirst( e: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "offerFirst", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.offerFirst_MethodID_45, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open func offerFirst( _ _e: java_swift.JavaObject? ) -> Bool {
        return offerFirst( e: _e )
    }

    /// public abstract boolean java.util.Deque.offerLast(java.lang.Object)

    private static var offerLast_MethodID_46: jmethodID?

    open func offerLast( e: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "offerLast", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.offerLast_MethodID_46, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open func offerLast( _ _e: java_swift.JavaObject? ) -> Bool {
        return offerLast( e: _e )
    }

    /// public default java.util.stream.Stream java.util.Collection.parallelStream()

    private static var parallelStream_MethodID_47: jmethodID?

    override open func parallelStream() -> Stream! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "parallelStream", methodSig: "()Ljava/util/stream/Stream;", methodCache: &DequeForward.parallelStream_MethodID_47, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? StreamForward( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.peek()

    private static var peek_MethodID_48: jmethodID?

    override open func peek() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "peek", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.peek_MethodID_48, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.peekFirst()

    private static var peekFirst_MethodID_49: jmethodID?

    open func peekFirst() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "peekFirst", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.peekFirst_MethodID_49, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.peekLast()

    private static var peekLast_MethodID_50: jmethodID?

    open func peekLast() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "peekLast", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.peekLast_MethodID_50, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.poll()

    private static var poll_MethodID_51: jmethodID?

    override open func poll() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "poll", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.poll_MethodID_51, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.pollFirst()

    private static var pollFirst_MethodID_52: jmethodID?

    open func pollFirst() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "pollFirst", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.pollFirst_MethodID_52, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.pollLast()

    private static var pollLast_MethodID_53: jmethodID?

    open func pollLast() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "pollLast", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.pollLast_MethodID_53, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object java.util.Deque.pop()

    private static var pop_MethodID_54: jmethodID?

    open func pop() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "pop", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.pop_MethodID_54, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract void java.util.Deque.push(java.lang.Object)

    private static var push_MethodID_55: jmethodID?

    open func push( e: java_swift.JavaObject? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "push", methodSig: "(Ljava/lang/Object;)V", methodCache: &DequeForward.push_MethodID_55, args: &__args, locals: &__locals )
    }

    open func push( _ _e: java_swift.JavaObject? ) {
        push( e: _e )
    }

    /// public abstract boolean java.util.Deque.remove(java.lang.Object)

    private static var remove_MethodID_56: jmethodID?

    override open func remove( o: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: o, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "remove", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.remove_MethodID_56, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func remove( _ _o: java_swift.JavaObject? ) -> Bool {
        return remove( o: _o )
    }

    /// public abstract java.lang.Object java.util.Deque.remove()

    private static var remove_MethodID_57: jmethodID?

    override open func remove() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "remove", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.remove_MethodID_57, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.Collection.removeAll(java.util.Collection)

    private static var removeAll_MethodID_58: jmethodID?

    override open func removeAll( c: Collection? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: c, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "removeAll", methodSig: "(Ljava/util/Collection;)Z", methodCache: &DequeForward.removeAll_MethodID_58, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func removeAll( _ _c: Collection? ) -> Bool {
        return removeAll( c: _c )
    }

    /// public abstract java.lang.Object java.util.Deque.removeFirst()

    private static var removeFirst_MethodID_59: jmethodID?

    open func removeFirst() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "removeFirst", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.removeFirst_MethodID_59, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.Deque.removeFirstOccurrence(java.lang.Object)

    private static var removeFirstOccurrence_MethodID_60: jmethodID?

    open func removeFirstOccurrence( o: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: o, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "removeFirstOccurrence", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.removeFirstOccurrence_MethodID_60, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open func removeFirstOccurrence( _ _o: java_swift.JavaObject? ) -> Bool {
        return removeFirstOccurrence( o: _o )
    }

    /// public default boolean java.util.Collection.removeIf(java.util.function.Predicate)

    private static var removeIf_MethodID_61: jmethodID?

    override open func removeIf( filter: Predicate? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: filter, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "removeIf", methodSig: "(Ljava/util/function/Predicate;)Z", methodCache: &DequeForward.removeIf_MethodID_61, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func removeIf( _ _filter: Predicate? ) -> Bool {
        return removeIf( filter: _filter )
    }

    /// public abstract java.lang.Object java.util.Deque.removeLast()

    private static var removeLast_MethodID_62: jmethodID?

    open func removeLast() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "removeLast", methodSig: "()Ljava/lang/Object;", methodCache: &DequeForward.removeLast_MethodID_62, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract boolean java.util.Deque.removeLastOccurrence(java.lang.Object)

    private static var removeLastOccurrence_MethodID_63: jmethodID?

    open func removeLastOccurrence( o: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: o, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "removeLastOccurrence", methodSig: "(Ljava/lang/Object;)Z", methodCache: &DequeForward.removeLastOccurrence_MethodID_63, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open func removeLastOccurrence( _ _o: java_swift.JavaObject? ) -> Bool {
        return removeLastOccurrence( o: _o )
    }

    /// public abstract boolean java.util.Collection.retainAll(java.util.Collection)

    private static var retainAll_MethodID_64: jmethodID?

    override open func retainAll( c: Collection? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: c, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "retainAll", methodSig: "(Ljava/util/Collection;)Z", methodCache: &DequeForward.retainAll_MethodID_64, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func retainAll( _ _c: Collection? ) -> Bool {
        return retainAll( c: _c )
    }

    /// public abstract int java.util.Deque.size()

    private static var size_MethodID_65: jmethodID?

    override open func size() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "size", methodSig: "()I", methodCache: &DequeForward.size_MethodID_65, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public default java.util.Spliterator java.util.Collection.spliterator()

    private static var spliterator_MethodID_66: jmethodID?

    override open func spliterator() -> Spliterator! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "spliterator", methodSig: "()Ljava/util/Spliterator;", methodCache: &DequeForward.spliterator_MethodID_66, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? SpliteratorForward( javaObject: __return ) : nil
    }


    /// public default java.util.stream.Stream java.util.Collection.stream()

    private static var stream_MethodID_67: jmethodID?

    override open func stream() -> Stream! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "stream", methodSig: "()Ljava/util/stream/Stream;", methodCache: &DequeForward.stream_MethodID_67, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? StreamForward( javaObject: __return ) : nil
    }


    /// public abstract java.lang.Object[] java.util.Collection.toArray(java.lang.Object[])

    private static var toArray_MethodID_68: jmethodID?

    override open func toArray( a: [JavaObject]? ) -> [JavaObject]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: a, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "toArray", methodSig: "([Ljava/lang/Object;)[Ljava/lang/Object;", methodCache: &DequeForward.toArray_MethodID_68, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [JavaObject].self, from: __return )
    }

    override open func toArray( _ _a: [JavaObject]? ) -> [JavaObject]! {
        return toArray( a: _a )
    }

    /// public abstract java.lang.Object[] java.util.Collection.toArray()

    private static var toArray_MethodID_69: jmethodID?

    override open func toArray() -> [JavaObject]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "toArray", methodSig: "()[Ljava/lang/Object;", methodCache: &DequeForward.toArray_MethodID_69, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [JavaObject].self, from: __return )
    }


}

