
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.util.function.Function ///

public protocol Function: JavaProtocol {

    /// public static java.util.function.Function java.util.function.Function.identity()

    //    class func identity() -> Function!

    /// private static java.lang.Object java.util.function.Function.lambda$identity$2(java.lang.Object)

    /// public default java.util.function.Function java.util.function.Function.andThen(java.util.function.Function)

    func andThen( after: Function? ) -> Function!

    /// public abstract java.lang.Object java.util.function.Function.apply(java.lang.Object)

    func apply( t: java_swift.JavaObject? ) -> java_swift.JavaObject!

    /// public default java.util.function.Function java.util.function.Function.compose(java.util.function.Function)

    func compose( before: Function? ) -> Function!

    /// private java.lang.Object java.util.function.Function.lambda$andThen$1(java.util.function.Function,java.lang.Object)

    /// private java.lang.Object java.util.function.Function.lambda$compose$0(java.util.function.Function,java.lang.Object)

}


open class FunctionForward: JNIObjectForward, Function {

    private static var FunctionJNIClass: jclass?

    /// public static java.util.function.Function java.util.function.Function.identity()

    private static var identity_MethodID_5: jmethodID?

    open class func identity() -> Function! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/util/function/Function", classCache: &FunctionJNIClass, methodName: "identity", methodSig: "()Ljava/util/function/Function;", methodCache: &identity_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FunctionForward( javaObject: __return ) : nil
    }


    /// public default java.util.function.Function java.util.function.Function.andThen(java.util.function.Function)

    private static var andThen_MethodID_6: jmethodID?

    open func andThen( after: Function? ) -> Function! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: after, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "andThen", methodSig: "(Ljava/util/function/Function;)Ljava/util/function/Function;", methodCache: &FunctionForward.andThen_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FunctionForward( javaObject: __return ) : nil
    }

    open func andThen( _ _after: Function? ) -> Function! {
        return andThen( after: _after )
    }

    /// public abstract java.lang.Object java.util.function.Function.apply(java.lang.Object)

    private static var apply_MethodID_7: jmethodID?

    open func apply( t: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: t, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "apply", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &FunctionForward.apply_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    open func apply( _ _t: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return apply( t: _t )
    }

    /// public default java.util.function.Function java.util.function.Function.compose(java.util.function.Function)

    private static var compose_MethodID_8: jmethodID?

    open func compose( before: Function? ) -> Function! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: before, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "compose", methodSig: "(Ljava/util/function/Function;)Ljava/util/function/Function;", methodCache: &FunctionForward.compose_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? FunctionForward( javaObject: __return ) : nil
    }

    open func compose( _ _before: Function? ) -> Function! {
        return compose( before: _before )
    }

}

