
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:53 GMT 2016 ///

/// class java.util.logging.Formatter ///

open class logging_Formatter: java_lang.JavaObject {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.util.logging.Formatter", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var logging_FormatterJNIClass: jclass?

    /// protected java.util.logging.Formatter()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "java/util/logging/Formatter", classCache: &logging_Formatter.logging_FormatterJNIClass, methodSig: "()V", methodCache: &logging_Formatter.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public abstract java.lang.String java.util.logging.Formatter.format(java.util.logging.LogRecord)

    private static var format_MethodID_2: jmethodID?

    open func format( arg0: LogRecord? ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "format", methodSig: "(Ljava/util/logging/LogRecord;)Ljava/lang/String;", methodCache: &logging_Formatter.format_MethodID_2, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open func format( _ _arg0: LogRecord? ) -> String! {
        return format( arg0: _arg0 )
    }

    /// public java.lang.String java.util.logging.Formatter.getHead(java.util.logging.Handler)

    private static var getHead_MethodID_3: jmethodID?

    open func getHead( arg0: Handler? ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getHead", methodSig: "(Ljava/util/logging/Handler;)Ljava/lang/String;", methodCache: &logging_Formatter.getHead_MethodID_3, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open func getHead( _ _arg0: Handler? ) -> String! {
        return getHead( arg0: _arg0 )
    }

    /// public java.lang.String java.util.logging.Formatter.getTail(java.util.logging.Handler)

    private static var getTail_MethodID_4: jmethodID?

    open func getTail( arg0: Handler? ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getTail", methodSig: "(Ljava/util/logging/Handler;)Ljava/lang/String;", methodCache: &logging_Formatter.getTail_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open func getTail( _ _arg0: Handler? ) -> String! {
        return getTail( arg0: _arg0 )
    }

    /// public synchronized java.lang.String java.util.logging.Formatter.formatMessage(java.util.logging.LogRecord)

    private static var formatMessage_MethodID_5: jmethodID?

    open func formatMessage( arg0: LogRecord? ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "formatMessage", methodSig: "(Ljava/util/logging/LogRecord;)Ljava/lang/String;", methodCache: &logging_Formatter.formatMessage_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open func formatMessage( _ _arg0: LogRecord? ) -> String! {
        return formatMessage( arg0: _arg0 )
    }

}
