
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.util.concurrent.atomic.LongAccumulator ///

open class LongAccumulator: /* java.util.concurrent.atomic.Striped64 */ UnclassedObject {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var LongAccumulatorJNIClass: jclass?

    /// private static final long java.util.concurrent.atomic.LongAccumulator.serialVersionUID

    /// private final java.util.function.LongBinaryOperator java.util.concurrent.atomic.LongAccumulator.function

    /// private final long java.util.concurrent.atomic.LongAccumulator.identity

    /// static final int java.util.concurrent.atomic.Striped64.NCPU

    /// transient volatile java.util.concurrent.atomic.Striped64$Cell[] java.util.concurrent.atomic.Striped64.cells

    /// transient volatile long java.util.concurrent.atomic.Striped64.base

    /// transient volatile int java.util.concurrent.atomic.Striped64.cellsBusy

    /// private static final sun.misc.Unsafe java.util.concurrent.atomic.Striped64.UNSAFE

    /// private static final long java.util.concurrent.atomic.Striped64.BASE

    /// private static final long java.util.concurrent.atomic.Striped64.CELLSBUSY

    /// private static final long java.util.concurrent.atomic.Striped64.PROBE

    /// private static final long java.lang.Number.serialVersionUID

    /// public java.util.concurrent.atomic.LongAccumulator(java.util.function.LongBinaryOperator,long)

    private static var new_MethodID_1: jmethodID?

    public convenience init( accumulatorFunction: LongBinaryOperator?, identity: Int64 ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: accumulatorFunction, locals: &__locals )
        __args[1] = JNIType.toJava( value: identity, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/concurrent/atomic/LongAccumulator", classCache: &LongAccumulator.LongAccumulatorJNIClass, methodSig: "(Ljava/util/function/LongBinaryOperator;J)V", methodCache: &LongAccumulator.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _accumulatorFunction: LongBinaryOperator?, _ _identity: Int64 ) {
        self.init( accumulatorFunction: _accumulatorFunction, identity: _identity )
    }

    /// public long java.util.concurrent.atomic.LongAccumulator.get()

    private static var get_MethodID_2: jmethodID?

    open func get() -> Int64 {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "get", methodSig: "()J", methodCache: &LongAccumulator.get_MethodID_2, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Int64(), from: __return )
    }


    /// public java.lang.String java.util.concurrent.atomic.LongAccumulator.toString()

    /// public int java.util.concurrent.atomic.LongAccumulator.intValue()

    /// public long java.util.concurrent.atomic.LongAccumulator.longValue()

    /// public float java.util.concurrent.atomic.LongAccumulator.floatValue()

    /// public double java.util.concurrent.atomic.LongAccumulator.doubleValue()

    /// static long java.util.concurrent.atomic.LongAccumulator.access$100(java.util.concurrent.atomic.LongAccumulator)

    /// static java.util.function.LongBinaryOperator java.util.concurrent.atomic.LongAccumulator.access$000(java.util.concurrent.atomic.LongAccumulator)

    /// private void java.util.concurrent.atomic.LongAccumulator.readObject(java.io.ObjectInputStream) throws java.io.InvalidObjectException

    /// public void java.util.concurrent.atomic.LongAccumulator.reset()

    private static var reset_MethodID_3: jmethodID?

    open func reset() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "reset", methodSig: "()V", methodCache: &LongAccumulator.reset_MethodID_3, args: &__args, locals: &__locals )
    }


    /// private java.lang.Object java.util.concurrent.atomic.LongAccumulator.writeReplace()

    /// public void java.util.concurrent.atomic.LongAccumulator.accumulate(long)

    private static var accumulate_MethodID_4: jmethodID?

    open func accumulate( x: Int64 ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: x, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "accumulate", methodSig: "(J)V", methodCache: &LongAccumulator.accumulate_MethodID_4, args: &__args, locals: &__locals )
    }

    open func accumulate( _ _x: Int64 ) {
        accumulate( x: _x )
    }

    /// public long java.util.concurrent.atomic.LongAccumulator.getThenReset()

    private static var getThenReset_MethodID_5: jmethodID?

    open func getThenReset() -> Int64 {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "getThenReset", methodSig: "()J", methodCache: &LongAccumulator.getThenReset_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Int64(), from: __return )
    }


}

