
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.util.TreeMap ///

open class TreeMap: AbstractMap, java_lang.Cloneable, /* interface java.io.Serializable */ UnavailableProtocol {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.util.TreeMap", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var TreeMapJNIClass: jclass?

    /// private static final boolean java.util.TreeMap.BLACK

    /// private static final boolean java.util.TreeMap.RED

    /// private static final java.lang.Object java.util.TreeMap.UNBOUNDED

    /// private static final long java.util.TreeMap.serialVersionUID

    /// private final java.util.Comparator java.util.TreeMap.comparator

    /// private transient java.util.NavigableMap java.util.TreeMap.descendingMap

    /// private transient java.util.TreeMap$EntrySet java.util.TreeMap.entrySet

    /// private transient int java.util.TreeMap.modCount

    /// private transient java.util.TreeMap$KeySet java.util.TreeMap.navigableKeySet

    /// private transient java.util.TreeMap$Entry java.util.TreeMap.root

    /// private transient int java.util.TreeMap.size

    /// transient java.util.Set java.util.AbstractMap.keySet

    // Skipping field: true false false false true false 

    /// transient java.util.Collection java.util.AbstractMap.values

    // Skipping field: true false false false true false 

    /// public java.util.TreeMap()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __object = JNIMethod.NewObject( className: "java/util/TreeMap", classCache: &TreeMap.TreeMapJNIClass, methodSig: "()V", methodCache: &TreeMap.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.util.TreeMap(java.util.Comparator)

    private static var new_MethodID_2: jmethodID?

    public convenience init( comparator: JavaComparator? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: comparator, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/TreeMap", classCache: &TreeMap.TreeMapJNIClass, methodSig: "(Ljava/util/Comparator;)V", methodCache: &TreeMap.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _comparator: JavaComparator? ) {
        self.init( comparator: _comparator )
    }

    /// public java.util.TreeMap(java.util.SortedMap)

    private static var new_MethodID_3: jmethodID?

    public convenience init( m: SortedMap? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: m, mapClass: "java/util/SortedMap", locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/TreeMap", classCache: &TreeMap.TreeMapJNIClass, methodSig: "(Ljava/util/SortedMap;)V", methodCache: &TreeMap.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _m: SortedMap? ) {
        self.init( m: _m )
    }

    /// public java.util.TreeMap(java.util.Map)

    private static var new_MethodID_4: jmethodID?

    public convenience init( m: java_swift.JavaMap? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: m, mapClass: "java/util/Map", locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/TreeMap", classCache: &TreeMap.TreeMapJNIClass, methodSig: "(Ljava/util/Map;)V", methodCache: &TreeMap.new_MethodID_4, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _m: java_swift.JavaMap? ) {
        self.init( m: _m )
    }

    /// static void java.util.TreeMap.access$000(java.util.TreeMap,java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// static int java.util.TreeMap.access$100(java.util.TreeMap)

    // Skipping method: true false false false false 

    /// static java.lang.Object java.util.TreeMap.access$200()

    // Skipping method: true false false false false 

    /// static java.util.Comparator java.util.TreeMap.access$300(java.util.TreeMap)

    // Skipping method: true false false false false 

    /// static int java.util.TreeMap.access$400(java.util.TreeMap)

    // Skipping method: true false false false false 

    /// static java.util.TreeMap$Entry java.util.TreeMap.access$500(java.util.TreeMap)

    // Skipping method: true false false false false 

    /// private static boolean java.util.TreeMap.colorOf(java.util.TreeMap$Entry)

    /// private static int java.util.TreeMap.computeRedLevel(int)

    /// static java.util.Map$Entry java.util.TreeMap.exportEntry(java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// static java.lang.Object java.util.TreeMap.key(java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// static java.lang.Object java.util.TreeMap.keyOrNull(java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// static java.util.Spliterator java.util.TreeMap.keySpliteratorFor(java.util.NavigableMap)

    // Skipping method: true false false false false 

    /// private static java.util.TreeMap$Entry java.util.TreeMap.leftOf(java.util.TreeMap$Entry)

    /// private static java.util.TreeMap$Entry java.util.TreeMap.parentOf(java.util.TreeMap$Entry)

    /// static java.util.TreeMap$Entry java.util.TreeMap.predecessor(java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// private static java.util.TreeMap$Entry java.util.TreeMap.rightOf(java.util.TreeMap$Entry)

    /// private static void java.util.TreeMap.setColor(java.util.TreeMap$Entry,boolean)

    /// static java.util.TreeMap$Entry java.util.TreeMap.successor(java.util.TreeMap$Entry)

    // Skipping method: true false false false false 

    /// static final boolean java.util.TreeMap.valEquals(java.lang.Object,java.lang.Object)

    // Skipping method: true false false false false 

    /// void java.util.TreeMap.addAllForTreeSet(java.util.SortedSet,java.lang.Object)

    // Skipping method: true false false false false 

    /// private final java.util.TreeMap$Entry java.util.TreeMap.buildFromSorted(int,int,int,int,java.util.Iterator,java.io.ObjectInputStream,java.lang.Object) throws java.io.IOException,java.lang.ClassNotFoundException

    /// private void java.util.TreeMap.buildFromSorted(int,java.util.Iterator,java.io.ObjectInputStream,java.lang.Object) throws java.io.IOException,java.lang.ClassNotFoundException

    /// public java.util.Map$Entry java.util.TreeMap.ceilingEntry(java.lang.Object)

    private static var ceilingEntry_MethodID_5: jmethodID?

    open func ceilingEntry( key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "ceilingEntry", methodSig: "(Ljava/lang/Object;)Ljava/util/Map$Entry;", methodCache: &TreeMap.ceilingEntry_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }

    open func ceilingEntry( _ _key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        return ceilingEntry( key: _key )
    }

    /// public java.lang.Object java.util.TreeMap.ceilingKey(java.lang.Object)

    private static var ceilingKey_MethodID_6: jmethodID?

    open func ceilingKey( key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "ceilingKey", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.ceilingKey_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    open func ceilingKey( _ _key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return ceilingKey( key: _key )
    }

    /// public void java.util.TreeMap.clear()

    // Skipping method: false true false false false 

    /// public java.lang.Object java.util.TreeMap.clone()

    private static var clone_MethodID_7: jmethodID?

    override open func clone() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "clone", methodSig: "()Ljava/lang/Object;", methodCache: &TreeMap.clone_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public java.util.Comparator java.util.TreeMap.comparator()

    private static var comparator_MethodID_8: jmethodID?

    open func comparator() -> JavaComparator! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "comparator", methodSig: "()Ljava/util/Comparator;", methodCache: &TreeMap.comparator_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaComparatorForward( javaObject: __return ) : nil
    }


    /// final int java.util.TreeMap.compare(java.lang.Object,java.lang.Object)

    // Skipping method: true false false false false 

    /// public boolean java.util.TreeMap.containsKey(java.lang.Object)

    // Skipping method: false true false false false 

    /// public boolean java.util.TreeMap.containsValue(java.lang.Object)

    // Skipping method: false true false false false 

    /// private void java.util.TreeMap.deleteEntry(java.util.TreeMap$Entry)

    /// java.util.Iterator java.util.TreeMap.descendingKeyIterator()

    // Skipping method: true false false false false 

    /// public java.util.NavigableSet java.util.TreeMap.descendingKeySet()

    private static var descendingKeySet_MethodID_9: jmethodID?

    open func descendingKeySet() -> NavigableSet! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "descendingKeySet", methodSig: "()Ljava/util/NavigableSet;", methodCache: &TreeMap.descendingKeySet_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? NavigableSetForward( javaObject: __return ) : nil
    }


    /// final java.util.Spliterator java.util.TreeMap.descendingKeySpliterator()

    // Skipping method: true false false false false 

    /// public java.util.NavigableMap java.util.TreeMap.descendingMap()

    private static var descendingMap_MethodID_10: jmethodID?

    open func descendingMap() -> NavigableMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "descendingMap", methodSig: "()Ljava/util/NavigableMap;", methodCache: &TreeMap.descendingMap_MethodID_10, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: NavigableMapForward.self, from: __return )
    }


    /// public java.util.Set java.util.TreeMap.entrySet()

    // Skipping method: false true false false false 

    /// public java.util.Map$Entry java.util.TreeMap.firstEntry()

    private static var firstEntry_MethodID_11: jmethodID?

    open func firstEntry() -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "firstEntry", methodSig: "()Ljava/util/Map$Entry;", methodCache: &TreeMap.firstEntry_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// public java.lang.Object java.util.TreeMap.firstKey()

    private static var firstKey_MethodID_12: jmethodID?

    open func firstKey() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "firstKey", methodSig: "()Ljava/lang/Object;", methodCache: &TreeMap.firstKey_MethodID_12, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// private void java.util.TreeMap.fixAfterDeletion(java.util.TreeMap$Entry)

    /// private void java.util.TreeMap.fixAfterInsertion(java.util.TreeMap$Entry)

    /// public java.util.Map$Entry java.util.TreeMap.floorEntry(java.lang.Object)

    private static var floorEntry_MethodID_13: jmethodID?

    open func floorEntry( key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "floorEntry", methodSig: "(Ljava/lang/Object;)Ljava/util/Map$Entry;", methodCache: &TreeMap.floorEntry_MethodID_13, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }

    open func floorEntry( _ _key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        return floorEntry( key: _key )
    }

    /// public java.lang.Object java.util.TreeMap.floorKey(java.lang.Object)

    private static var floorKey_MethodID_14: jmethodID?

    open func floorKey( key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "floorKey", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.floorKey_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    open func floorKey( _ _key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return floorKey( key: _key )
    }

    /// public void java.util.TreeMap.forEach(java.util.function.BiConsumer)

    private static var forEach_MethodID_15: jmethodID?

    override open func forEach( arg0: BiConsumer? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "forEach", methodSig: "(Ljava/util/function/BiConsumer;)V", methodCache: &TreeMap.forEach_MethodID_15, args: &__args, locals: &__locals )
    }

    override open func forEach( _ _arg0: BiConsumer? ) {
        forEach( arg0: _arg0 )
    }

    /// public java.lang.Object java.util.TreeMap.get(java.lang.Object)

    // Skipping method: false true false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getCeilingEntry(java.lang.Object)

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getEntry(java.lang.Object)

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getEntryUsingComparator(java.lang.Object)

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getFirstEntry()

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getFloorEntry(java.lang.Object)

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getHigherEntry(java.lang.Object)

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getLastEntry()

    // Skipping method: true false false false false 

    /// final java.util.TreeMap$Entry java.util.TreeMap.getLowerEntry(java.lang.Object)

    // Skipping method: true false false false false 

    /// public java.util.SortedMap java.util.TreeMap.headMap(java.lang.Object)

    private static var headMap_MethodID_16: jmethodID?

    open func headMap( toKey: java_swift.JavaObject? ) -> SortedMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: toKey, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "headMap", methodSig: "(Ljava/lang/Object;)Ljava/util/SortedMap;", methodCache: &TreeMap.headMap_MethodID_16, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: SortedMapForward.self, from: __return )
    }

    open func headMap( _ _toKey: java_swift.JavaObject? ) -> SortedMap! {
        return headMap( toKey: _toKey )
    }

    /// public java.util.NavigableMap java.util.TreeMap.headMap(java.lang.Object,boolean)

    private static var headMap_MethodID_17: jmethodID?

    open func headMap( toKey: java_swift.JavaObject?, inclusive: Bool ) -> NavigableMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: toKey, locals: &__locals )
        __args[1] = jvalue( z: jboolean(inclusive ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "headMap", methodSig: "(Ljava/lang/Object;Z)Ljava/util/NavigableMap;", methodCache: &TreeMap.headMap_MethodID_17, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: NavigableMapForward.self, from: __return )
    }

    open func headMap( _ _toKey: java_swift.JavaObject?, _ _inclusive: Bool ) -> NavigableMap! {
        return headMap( toKey: _toKey, inclusive: _inclusive )
    }

    /// public java.util.Map$Entry java.util.TreeMap.higherEntry(java.lang.Object)

    private static var higherEntry_MethodID_18: jmethodID?

    open func higherEntry( key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "higherEntry", methodSig: "(Ljava/lang/Object;)Ljava/util/Map$Entry;", methodCache: &TreeMap.higherEntry_MethodID_18, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }

    open func higherEntry( _ _key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        return higherEntry( key: _key )
    }

    /// public java.lang.Object java.util.TreeMap.higherKey(java.lang.Object)

    private static var higherKey_MethodID_19: jmethodID?

    open func higherKey( key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "higherKey", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.higherKey_MethodID_19, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    open func higherKey( _ _key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return higherKey( key: _key )
    }

    /// java.util.Iterator java.util.TreeMap.keyIterator()

    // Skipping method: true false false false false 

    /// public java.util.Set java.util.TreeMap.keySet()

    // Skipping method: false true false false false 

    /// final java.util.Spliterator java.util.TreeMap.keySpliterator()

    // Skipping method: true false false false false 

    /// public java.util.Map$Entry java.util.TreeMap.lastEntry()

    private static var lastEntry_MethodID_20: jmethodID?

    open func lastEntry() -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "lastEntry", methodSig: "()Ljava/util/Map$Entry;", methodCache: &TreeMap.lastEntry_MethodID_20, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// public java.lang.Object java.util.TreeMap.lastKey()

    private static var lastKey_MethodID_21: jmethodID?

    open func lastKey() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "lastKey", methodSig: "()Ljava/lang/Object;", methodCache: &TreeMap.lastKey_MethodID_21, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public java.util.Map$Entry java.util.TreeMap.lowerEntry(java.lang.Object)

    private static var lowerEntry_MethodID_22: jmethodID?

    open func lowerEntry( key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "lowerEntry", methodSig: "(Ljava/lang/Object;)Ljava/util/Map$Entry;", methodCache: &TreeMap.lowerEntry_MethodID_22, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }

    open func lowerEntry( _ _key: java_swift.JavaObject? ) -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        return lowerEntry( key: _key )
    }

    /// public java.lang.Object java.util.TreeMap.lowerKey(java.lang.Object)

    private static var lowerKey_MethodID_23: jmethodID?

    open func lowerKey( key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: key, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "lowerKey", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.lowerKey_MethodID_23, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    open func lowerKey( _ _key: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return lowerKey( key: _key )
    }

    /// public java.util.NavigableSet java.util.TreeMap.navigableKeySet()

    private static var navigableKeySet_MethodID_24: jmethodID?

    open func navigableKeySet() -> NavigableSet! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "navigableKeySet", methodSig: "()Ljava/util/NavigableSet;", methodCache: &TreeMap.navigableKeySet_MethodID_24, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? NavigableSetForward( javaObject: __return ) : nil
    }


    /// public java.util.Map$Entry java.util.TreeMap.pollFirstEntry()

    private static var pollFirstEntry_MethodID_25: jmethodID?

    open func pollFirstEntry() -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "pollFirstEntry", methodSig: "()Ljava/util/Map$Entry;", methodCache: &TreeMap.pollFirstEntry_MethodID_25, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// public java.util.Map$Entry java.util.TreeMap.pollLastEntry()

    private static var pollLastEntry_MethodID_26: jmethodID?

    open func pollLastEntry() -> /* interface java.util.Map$Entry */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "pollLastEntry", methodSig: "()Ljava/util/Map$Entry;", methodCache: &TreeMap.pollLastEntry_MethodID_26, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.util.Map$Entry */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// public java.lang.Object java.util.TreeMap.put(java.lang.Object,java.lang.Object)

    // Skipping method: false true false false false 

    /// public void java.util.TreeMap.putAll(java.util.Map)

    private static var putAll_MethodID_27: jmethodID?

    override open func putAll( arg0: java_swift.JavaMap? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, mapClass: "java/util/Map", locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "putAll", methodSig: "(Ljava/util/Map;)V", methodCache: &TreeMap.putAll_MethodID_27, args: &__args, locals: &__locals )
    }

    override open func putAll( _ _arg0: java_swift.JavaMap? ) {
        putAll( arg0: _arg0 )
    }

    /// private void java.util.TreeMap.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException

    /// void java.util.TreeMap.readTreeSet(int,java.io.ObjectInputStream,java.lang.Object) throws java.io.IOException,java.lang.ClassNotFoundException

    // Skipping method: true false false false false 

    /// public java.lang.Object java.util.TreeMap.remove(java.lang.Object)

    // Skipping method: false true false false false 

    /// public java.lang.Object java.util.TreeMap.replace(java.lang.Object,java.lang.Object)

    private static var replace_MethodID_28: jmethodID?

    override open func replace( arg0: java_swift.JavaObject?, arg1: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "replace", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.replace_MethodID_28, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    override open func replace( _ _arg0: java_swift.JavaObject?, _ _arg1: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return replace( arg0: _arg0, arg1: _arg1 )
    }

    /// public boolean java.util.TreeMap.replace(java.lang.Object,java.lang.Object,java.lang.Object)

    private static var replace_MethodID_29: jmethodID?

    override open func replace( arg0: java_swift.JavaObject?, arg1: java_swift.JavaObject?, arg2: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "replace", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z", methodCache: &TreeMap.replace_MethodID_29, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func replace( _ _arg0: java_swift.JavaObject?, _ _arg1: java_swift.JavaObject?, _ _arg2: java_swift.JavaObject? ) -> Bool {
        return replace( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// public void java.util.TreeMap.replaceAll(java.util.function.BiFunction)

    private static var replaceAll_MethodID_30: jmethodID?

    override open func replaceAll( arg0: BiFunction? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "replaceAll", methodSig: "(Ljava/util/function/BiFunction;)V", methodCache: &TreeMap.replaceAll_MethodID_30, args: &__args, locals: &__locals )
    }

    override open func replaceAll( _ _arg0: BiFunction? ) {
        replaceAll( arg0: _arg0 )
    }

    /// private void java.util.TreeMap.rotateLeft(java.util.TreeMap$Entry)

    /// private void java.util.TreeMap.rotateRight(java.util.TreeMap$Entry)

    /// public int java.util.TreeMap.size()

    // Skipping method: false true false false false 

    /// public java.util.NavigableMap java.util.TreeMap.subMap(java.lang.Object,boolean,java.lang.Object,boolean)

    private static var subMap_MethodID_31: jmethodID?

    open func subMap( fromKey: java_swift.JavaObject?, fromInclusive: Bool, toKey: java_swift.JavaObject?, toInclusive: Bool ) -> NavigableMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 4 )
        __args[0] = JNIType.toJava( value: fromKey, locals: &__locals )
        __args[1] = jvalue( z: jboolean(fromInclusive ? JNI_TRUE : JNI_FALSE) )
        __args[2] = JNIType.toJava( value: toKey, locals: &__locals )
        __args[3] = jvalue( z: jboolean(toInclusive ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "subMap", methodSig: "(Ljava/lang/Object;ZLjava/lang/Object;Z)Ljava/util/NavigableMap;", methodCache: &TreeMap.subMap_MethodID_31, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: NavigableMapForward.self, from: __return )
    }

    open func subMap( _ _fromKey: java_swift.JavaObject?, _ _fromInclusive: Bool, _ _toKey: java_swift.JavaObject?, _ _toInclusive: Bool ) -> NavigableMap! {
        return subMap( fromKey: _fromKey, fromInclusive: _fromInclusive, toKey: _toKey, toInclusive: _toInclusive )
    }

    /// public java.util.SortedMap java.util.TreeMap.subMap(java.lang.Object,java.lang.Object)

    private static var subMap_MethodID_32: jmethodID?

    open func subMap( fromKey: java_swift.JavaObject?, toKey: java_swift.JavaObject? ) -> SortedMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: fromKey, locals: &__locals )
        __args[1] = JNIType.toJava( value: toKey, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "subMap", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/SortedMap;", methodCache: &TreeMap.subMap_MethodID_32, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: SortedMapForward.self, from: __return )
    }

    open func subMap( _ _fromKey: java_swift.JavaObject?, _ _toKey: java_swift.JavaObject? ) -> SortedMap! {
        return subMap( fromKey: _fromKey, toKey: _toKey )
    }

    /// public java.util.SortedMap java.util.TreeMap.tailMap(java.lang.Object)

    private static var tailMap_MethodID_33: jmethodID?

    open func tailMap( fromKey: java_swift.JavaObject? ) -> SortedMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: fromKey, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "tailMap", methodSig: "(Ljava/lang/Object;)Ljava/util/SortedMap;", methodCache: &TreeMap.tailMap_MethodID_33, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: SortedMapForward.self, from: __return )
    }

    open func tailMap( _ _fromKey: java_swift.JavaObject? ) -> SortedMap! {
        return tailMap( fromKey: _fromKey )
    }

    /// public java.util.NavigableMap java.util.TreeMap.tailMap(java.lang.Object,boolean)

    private static var tailMap_MethodID_34: jmethodID?

    open func tailMap( fromKey: java_swift.JavaObject?, inclusive: Bool ) -> NavigableMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: fromKey, locals: &__locals )
        __args[1] = jvalue( z: jboolean(inclusive ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "tailMap", methodSig: "(Ljava/lang/Object;Z)Ljava/util/NavigableMap;", methodCache: &TreeMap.tailMap_MethodID_34, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: NavigableMapForward.self, from: __return )
    }

    open func tailMap( _ _fromKey: java_swift.JavaObject?, _ _inclusive: Bool ) -> NavigableMap! {
        return tailMap( fromKey: _fromKey, inclusive: _inclusive )
    }

    /// public java.util.Collection java.util.TreeMap.values()

    // Skipping method: false true false false false 

    /// private void java.util.TreeMap.writeObject(java.io.ObjectOutputStream) throws java.io.IOException

    /// In declared protocol but not defined.. ///

    /// public abstract void java.util.Map.clear()

    // Skipping method: false true false false false 

    /// public default java.lang.Object java.util.Map.compute(java.lang.Object,java.util.function.BiFunction)

    // Skipping method: false true false false false 

    /// public default java.lang.Object java.util.Map.computeIfAbsent(java.lang.Object,java.util.function.Function)

    // Skipping method: false true false false false 

    /// public default java.lang.Object java.util.Map.computeIfPresent(java.lang.Object,java.util.function.BiFunction)

    // Skipping method: false true false false false 

    /// public abstract boolean java.util.Map.containsKey(java.lang.Object)

    private static var containsKey_MethodID_35: jmethodID?

    override open func containsKey( arg0: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "containsKey", methodSig: "(Ljava/lang/Object;)Z", methodCache: &TreeMap.containsKey_MethodID_35, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func containsKey( _ _arg0: java_swift.JavaObject? ) -> Bool {
        return containsKey( arg0: _arg0 )
    }

    /// public abstract boolean java.util.Map.containsValue(java.lang.Object)

    private static var containsValue_MethodID_36: jmethodID?

    override open func containsValue( arg0: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "containsValue", methodSig: "(Ljava/lang/Object;)Z", methodCache: &TreeMap.containsValue_MethodID_36, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func containsValue( _ _arg0: java_swift.JavaObject? ) -> Bool {
        return containsValue( arg0: _arg0 )
    }

    /// public abstract java.util.Set java.util.Map.entrySet()

    // Skipping method: false true false false false 

    /// public abstract boolean java.util.Map.equals(java.lang.Object)

    private static var equals_MethodID_37: jmethodID?

    override open func equals( arg0: java_swift.JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "equals", methodSig: "(Ljava/lang/Object;)Z", methodCache: &TreeMap.equals_MethodID_37, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    override open func equals( _ _arg0: java_swift.JavaObject? ) -> Bool {
        return equals( arg0: _arg0 )
    }

    /// public abstract java.lang.Object java.util.Map.get(java.lang.Object)

    private static var get_MethodID_38: jmethodID?

    override open func get( arg0: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "get", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.get_MethodID_38, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    override open func get( _ _arg0: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return get( arg0: _arg0 )
    }

    /// public default java.lang.Object java.util.Map.getOrDefault(java.lang.Object,java.lang.Object)

    // Skipping method: false true false false false 

    /// public abstract int java.util.Map.hashCode()

    // Skipping method: false true false false false 

    /// public abstract boolean java.util.Map.isEmpty()

    // Skipping method: false true false false false 

    /// public abstract java.util.Set java.util.Map.keySet()

    // Skipping method: false true false false false 

    /// public default java.lang.Object java.util.Map.merge(java.lang.Object,java.lang.Object,java.util.function.BiFunction)

    // Skipping method: false true false false false 

    /// public abstract java.lang.Object java.util.Map.put(java.lang.Object,java.lang.Object)

    private static var put_MethodID_39: jmethodID?

    override open func put( arg0: java_swift.JavaObject?, arg1: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "put", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.put_MethodID_39, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    override open func put( _ _arg0: java_swift.JavaObject?, _ _arg1: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return put( arg0: _arg0, arg1: _arg1 )
    }

    /// public default java.lang.Object java.util.Map.putIfAbsent(java.lang.Object,java.lang.Object)

    // Skipping method: false true false false false 

    /// public abstract java.lang.Object java.util.Map.remove(java.lang.Object)

    private static var remove_MethodID_40: jmethodID?

    override open func remove( arg0: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "remove", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &TreeMap.remove_MethodID_40, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }

    override open func remove( _ _arg0: java_swift.JavaObject? ) -> java_swift.JavaObject! {
        return remove( arg0: _arg0 )
    }

    /// public default boolean java.util.Map.remove(java.lang.Object,java.lang.Object)

    // Skipping method: false true false false false 

    /// public abstract int java.util.Map.size()

    // Skipping method: false true false false false 

    /// public abstract java.util.Collection java.util.Map.values()

    // Skipping method: false true false false false 

}

