
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.util.zip.ZipInputStream ///

open class ZipInputStream: InflaterInputStream {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var ZipInputStreamJNIClass: jclass?

    /// private java.util.zip.ZipEntry java.util.zip.ZipInputStream.entry

    /// private int java.util.zip.ZipInputStream.flag

    /// private java.util.zip.CRC32 java.util.zip.ZipInputStream.crc

    /// private long java.util.zip.ZipInputStream.remaining

    /// private byte[] java.util.zip.ZipInputStream.tmpbuf

    /// private static final int java.util.zip.ZipInputStream.STORED

    /// private static final int java.util.zip.ZipInputStream.DEFLATED

    /// private boolean java.util.zip.ZipInputStream.closed

    /// private boolean java.util.zip.ZipInputStream.entryEOF

    /// private java.util.zip.ZipCoder java.util.zip.ZipInputStream.zc

    /// private byte[] java.util.zip.ZipInputStream.b

    /// protected java.util.zip.Inflater java.util.zip.InflaterInputStream.inf

    private static var inf_FieldID: jfieldID?

    override open var inf: Inflater! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "inf", fieldType: "Ljava/util/zip/Inflater;", fieldCache: &ZipInputStream.inf_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? Inflater( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue != nil ? newValue! as JNIObject : nil, locals: &__locals )
            JNIField.SetObjectField( fieldName: "inf", fieldType: "Ljava/util/zip/Inflater;", fieldCache: &ZipInputStream.inf_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected byte[] java.util.zip.InflaterInputStream.buf

    private static var buf_FieldID: jfieldID?

    override open var buf: [Int8]! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "buf", fieldType: "[B", fieldCache: &ZipInputStream.buf_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: [Int8](), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "buf", fieldType: "[B", fieldCache: &ZipInputStream.buf_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected int java.util.zip.InflaterInputStream.len

    private static var len_FieldID: jfieldID?

    override open var len: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "len", fieldType: "I", fieldCache: &ZipInputStream.len_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "len", fieldType: "I", fieldCache: &ZipInputStream.len_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// private boolean java.util.zip.InflaterInputStream.closed

    /// private boolean java.util.zip.InflaterInputStream.reachEOF

    /// boolean java.util.zip.InflaterInputStream.usesDefaultInflater

    /// private byte[] java.util.zip.InflaterInputStream.singleByteBuf

    /// private byte[] java.util.zip.InflaterInputStream.b

    /// protected volatile java.io.InputStream java.io.FilterInputStream.in

    private static var _in_FieldID: jfieldID?

    override open var _in: /* java.io.InputStream */ UnclassedObject! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "in", fieldType: "Ljava/io/InputStream;", fieldCache: &ZipInputStream._in_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? /* java.io.InputStream */ UnclassedObject( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue != nil ? newValue! as JNIObject : nil, locals: &__locals )
            JNIField.SetObjectField( fieldName: "in", fieldType: "Ljava/io/InputStream;", fieldCache: &ZipInputStream._in_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private static final int java.io.InputStream.MAX_SKIP_BUFFER_SIZE

    /// public java.util.zip.ZipInputStream(java.io.InputStream,java.nio.charset.Charset)

    private static var new_MethodID_1: jmethodID?

    public convenience init( _in: /* java.io.InputStream */ UnclassedObject?, charset: /* java.nio.charset.Charset */ UnclassedObject? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: _in != nil ? _in! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: charset != nil ? charset! as JNIObject : nil, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/zip/ZipInputStream", classCache: &ZipInputStream.ZipInputStreamJNIClass, methodSig: "(Ljava/io/InputStream;Ljava/nio/charset/Charset;)V", methodCache: &ZipInputStream.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ __in: /* java.io.InputStream */ UnclassedObject?, _ _charset: /* java.nio.charset.Charset */ UnclassedObject? ) {
        self.init( _in: __in, charset: _charset )
    }

    /// public java.util.zip.ZipInputStream(java.io.InputStream)

    private static var new_MethodID_2: jmethodID?

    public convenience init( _in: /* java.io.InputStream */ UnclassedObject? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: _in != nil ? _in! as JNIObject : nil, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/zip/ZipInputStream", classCache: &ZipInputStream.ZipInputStreamJNIClass, methodSig: "(Ljava/io/InputStream;)V", methodCache: &ZipInputStream.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ __in: /* java.io.InputStream */ UnclassedObject? ) {
        self.init( _in: __in )
    }

    /// public int java.util.zip.ZipInputStream.read(byte[],int,int) throws java.io.IOException

    /// public void java.util.zip.ZipInputStream.close() throws java.io.IOException

    /// public long java.util.zip.ZipInputStream.skip(long) throws java.io.IOException

    /// public int java.util.zip.ZipInputStream.available() throws java.io.IOException

    /// private void java.util.zip.ZipInputStream.readFully(byte[],int,int) throws java.io.IOException

    /// private void java.util.zip.ZipInputStream.ensureOpen() throws java.io.IOException

    /// protected java.util.zip.ZipEntry java.util.zip.ZipInputStream.createZipEntry(java.lang.String)

    private static var createZipEntry_MethodID_3: jmethodID?

    open func createZipEntry( name: String? ) -> ZipEntry! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "createZipEntry", methodSig: "(Ljava/lang/String;)Ljava/util/zip/ZipEntry;", methodCache: &ZipInputStream.createZipEntry_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? ZipEntry( javaObject: __return ) : nil
    }

    open func createZipEntry( _ _name: String? ) -> ZipEntry! {
        return createZipEntry( name: _name )
    }

    /// public void java.util.zip.ZipInputStream.closeEntry() throws java.io.IOException

    private static var closeEntry_MethodID_4: jmethodID?

    open func closeEntry() throws /* java.io.IOException */ {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "closeEntry", methodSig: "()V", methodCache: &ZipInputStream.closeEntry_MethodID_4, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw /* java.io.IOException */ UnclassedObject( javaObject: throwable )
        }
    }


    /// private java.util.zip.ZipEntry java.util.zip.ZipInputStream.readLOC() throws java.io.IOException

    /// private void java.util.zip.ZipInputStream.readEnd(java.util.zip.ZipEntry) throws java.io.IOException

    /// public java.util.zip.ZipEntry java.util.zip.ZipInputStream.getNextEntry() throws java.io.IOException

    private static var getNextEntry_MethodID_5: jmethodID?

    open func getNextEntry() throws /* java.io.IOException */ -> ZipEntry! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getNextEntry", methodSig: "()Ljava/util/zip/ZipEntry;", methodCache: &ZipInputStream.getNextEntry_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw /* java.io.IOException */ UnclassedObject( javaObject: throwable )
        }
        return __return != nil ? ZipEntry( javaObject: __return ) : nil
    }


}

